included:
  - DibyDot

excluded:
  - Pods
  - DibyDotTests

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - joined_default_parameter
  - sorted_first_last
  - toggle_bool
  - unused_import
  - unused_optional_binding
  - redundant_discardable_let
  - redundant_nil_coalescing
  - prefer_self_type_over_type_of_self
  - closure_spacing
  - trailing_closure
  - mark
  - discouraged_optional_collection
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - line_length
  - force_cast
  - force_unwrapping
  - todo

custom_rules:
  no_get_prefix:
    name: "'get' 접두사 지양"
    regex: "func\\s+get[A-Z]"
    message: "데이터를 가져오는 함수의 경우 `get` 접두사는 지양해주세요. 대신 `request` 또는 `fetch` 사용을 고려해주세요."
    severity: warning

  method_name_lower_camel:
    name: "함수 이름은 lowerCamelCase"
    regex: "func\\s+[A-Z][a-zA-Z0-9]+"
    message: "함수 이름은 lowerCamelCase로 작성해주세요."
    severity: warning

  no_array_type_annotation:
    name: "타입 어노테이션은 단축형 사용"
    regex: "Array<.+>"
    message: "`Array<T>` 대신 `[T]` 형식을 사용해주세요."
    severity: warning

  no_dictionary_type_annotation:
    name: "타입 어노테이션은 단축형 사용"
    regex: "Dictionary<.+>"
    message: "`Dictionary<K, V>` 대신 `[K: V]` 형식을 사용해주세요."
    severity: warning

  no_uppercase_variable:
    name: "변수 이름은 lowerCamelCase"
    regex: "var\\s+[A-Z]"
    message: "변수 이름은 lowerCamelCase로 작성해주세요."
    severity: warning

  no_prefixed_struct_class:
    name: "Struct/Class 이름에 prefix 지양"
    regex: "(struct|class)\\s+rw[A-Z]"
    message: "Struct나 Class 이름에는 prefix(`rw`)를 사용하지 마세요."
    severity: warning

  no_multiple_layout_containers:
    name: "중첩된 레이아웃 컨테이너"
    regex: "(VStack|HStack|ZStack|Grid).+\\{[^}]+(VStack|HStack|ZStack|Grid)"
    message: "하나의 View에 레이아웃 컨테이너는 1개만 사용하도록 분리해주세요."
    severity: warning

  prefer_struct_view:
    name: "SwiftUI View는 Struct로 정의"
    regex: "@ViewBuilder\\s+(var|func)"
    message: "SwiftUI View는 @ViewBuilder보다 struct로 정의하는 것을 권장합니다."
    severity: warning

  no_mark_missing:
    name: "MARK 누락"
    regex: "^((?!MARK).)*$"
    match_kinds:
      - comment
    message: "섹션 구분에는 `// MARK:` 사용을 권장합니다."
    severity: warning

  prefer_access_control:
    name: "접근제어자 권장"
    regex: "^(func|class|struct|var|let)\\s+(?!private|fileprivate|internal|public|open)"
    message: "접근 제어자(private, public 등)를 명시해주세요."
    severity: warning

identifier_name:
  min_length:
    warning: 3
    error: 2
  excluded:
    - id
    - x
    - y
    - i
    - z

trailing_newline:
  warning: 1

file_length:
  warning: 400
  error: 1000

function_body_length:
  warning: 40
  error: 100

type_body_length:
  warning: 300
  error: 500
  